### ISSUE TITLE
Notifications + chat window + settings issues

### ISSUE THREAD

**Issue by arainot** [hrubymar10/goofy_swift#2]
Hi,

three issues with 4.0:

- Notifications do not work, even by setting it up on messenger.com, clicking on notifications does not make them appear on the desktop. I get the sound from a message but nothing else.
- The chat window is not correct, the left sidebar takes up too much space compared to the actual chat window. 
- Can't access the app's setting by pressing command + ,

**Comment by hrubymar10** [comment]
All bugs should be resolved with d22d437 in GoofySwift v4.2 release.

You can download it here: https://github.com/hrubymar10/goofy_swift/releases/tag/v4.2

Please confirm that all bugs were resolved.

**Comment by arainot** [comment]
Yes, it works perfectly now! Thanks a lot!

**Comment by hrubymar10** [comment]
Good. Glad to hear it. Closing
