### ISSUE TITLE
Add ability to choose theme

### ISSUE THREAD

**Issue by hrubymar10** [hrubymar10/goofy_swift#4]
Add dark theme, red theme, ...

**Comment by hrubymar10** [comment]
First Pre-Release is here! Please try and eventually open new issues.

Version: GoofySwift v4.3 Beta 1
Branch: [Dark-Mode](https://github.com/hrubymar10/goofy_swift/tree/Dark-Mode)
Commit: 10fed53ebc9f0018e3dba26d707d20aabd1e2635
Download: https://github.com/hrubymar10/goofy_swift/releases/tag/v4.3_Beta_1

**Comment by arainot** [comment]
Works great for me, no issues.

**Comment by hrubymar10** [comment]
Closing with #6
