### ISSUE TITLE
Crashes at startup

### ISSUE THREAD

**Issue by arainot** [hrubymar10/goofy_swift#5]
## Problem:
When I open the app it crashes. Happens on the latest versions.

## Steps to reproduce:
Open the app

## Info:
* **macOS Version:** 10.13.3
* **GoofySwift Version:** 4.3 beta 2 & 4.2

**Comment by hrubymar10** [comment]
Can you please also attach Crashlog?

Attach it for both v4.2 and 4.3 Beta 2

**Comment by arainot** [comment]
How do I get it?

**Comment by hrubymar10** [comment]
It should crash with message like this:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/2218817/36946372-350dc1ea-1fbc-11e8-9275-fd67469d872b.png">

So only just click on `Show Details` and copy&paste everything from there like this:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/2218817/36946380-5618a850-1fbc-11e8-8386-39a2e6ef336f.png">

**Comment by arainot** [comment]
Weird, it doesn't crash anymore... I'll keep you informed if it happens again.

**Comment by hrubymar10** [comment]
If it happens again, than please open new issue and include crashlog, otherwise I can't help you 😕 sorry

**Comment by arainot** [comment]
Sure!
